### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by stevsee** [jasonwynn10/PoliteTeleports#4]
A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: PoliteTeleports

Error: Cannot find a safe spawn point in non-generated terrain
File: pmsrc/src/world/World
Line: 2962
Type: pocketmine\world\WorldException

**Comment by jasonw4331** [comment]
Could you send the other 24 lines of the error message?

**Comment by LyanHudsson** [comment]
consulta este tp es para minecraft poketmine?,  como se instala? saludos.

**Comment by jasonw4331** [comment]
I've received no answer so I'll close this
